[package]
name = "lookbook"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[workspace]
members = [
    ".",
    "example"
]

[dependencies]
xilem_web = { git = "https://github.com/linebender/xilem" }
wasm-bindgen = "0.2.92"
web-sys = { version = "0.3.69", features = ["Node"] }
