[package]
name = "lookbook"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[workspace]
members = [
    ".",
    "macros"
]

[dependencies]
dioxus = { git = "https://github.com/dioxuslabs/dioxus" }
dioxus-web = { git = "https://github.com/dioxuslabs/dioxus" }
dioxus-signals = { git = "https://github.com/dioxuslabs/dioxus" }
dioxus-router = { git = "https://github.com/dioxuslabs/dioxus", features = ["web"] }
dioxus-material = { git = "https://github.com/matthunz/dioxus-material" }
dioxus-use-mounted = { git = "https://github.com/matthunz/dioxus-use-mounted" }
dioxus-resize-observer = { git = "https://github.com/dioxus-community/dioxus-resize-observer", rev = "1a16141a63dbb17230a3dacc97d949861aa2125f"  }
dioxus_markdown = { git = "https://github.com/matthunz/markdown" }
lookbook-macros = { path = "macros" }
serde_json = "1.0.107"
serde = "1.0.189"
